function needlecurvature20221010 = importfile(filename, dataLines)
%IMPORTFILE Import data from a text file
%  NEEDLECURVATURE20221010 = IMPORTFILE(FILENAME) reads data from text
%  file FILENAME for the default selection.  Returns the data as a table.
%
%  NEEDLECURVATURE20221010 = IMPORTFILE(FILE, DATALINES) reads data for
%  the specified row interval(s) of text file FILENAME. Specify
%  DATALINES as a positive scalar integer or a N-by-2 array of positive
%  scalar integers for dis-contiguous row intervals.
%
%  Example:
%  needlecurvature20221010 = importfile("/home/yanzhou/Documents/FBG_Matlab/write_to_file/needle_curvature_2022-10-10.txt", [2, Inf]);
%
%  See also READTABLE.
%
% Auto-generated by MATLAB on 10-Oct-2022 14:24:47

%% Input handling

% If dataLines is not specified, define defaults
if nargin < 2
    dataLines = [2, Inf];
end

%% Set up the Import Options and import the data
opts = delimitedTextImportOptions("NumVariables", 9);

% Specify range and delimiter
opts.DataLines = dataLines;
opts.Delimiter = "\t";

% Specify column names and types
opts.VariableNames = ["Var1", "XY_AA1", "XY_AA2", "XY_AA3", "XY_AA4", "XZ_AA1", "XZ_AA2", "XZ_AA3", "XZ_AA4"];
opts.SelectedVariableNames = ["XY_AA1", "XY_AA2", "XY_AA3", "XY_AA4", "XZ_AA1", "XZ_AA2", "XZ_AA3", "XZ_AA4"];
opts.VariableTypes = ["string", "double", "double", "double", "double", "double", "double", "double", "double"];

% Specify file level properties
opts.ExtraColumnsRule = "ignore";
opts.EmptyLineRule = "read";

% Specify variable properties
opts = setvaropts(opts, "Var1", "WhitespaceRule", "preserve");
opts = setvaropts(opts, "Var1", "EmptyFieldRule", "auto");

% Import the data
needlecurvature20221010 = readtable(filename, opts);

end